apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-landing-page-4
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/angeelsanchez/my-landing-page-4.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
